### ISSUE TITLE
Sample I/O

### ISSUE THREAD

**Issue by lemmingapex** [jzeimen/PuzzleSolver#1]
Could you add some sample input and output images?  Thanks!

**Comment by jzeimen** [comment]
Haha yeah I have only tested it for one data set so far, but I will put it
in the repo when I get home. Did you get it to compile?

On Apr 14, 2013, at 7:25 PM, Scott Wiedemann notifications@github.com
wrote:

Could you add some sample input and output images? Thanks!

—
Reply to this email directly or view it on
GitHubhttps://github.com/jzeimen/PuzzleSolver/issues/1
.

**Comment by lemmingapex** [comment]
Sweat, thanks. Excited to run it!  And yes, it compiled perfectly under Ubuntu 12.04.2 LTS.

**Comment by jzeimen** [comment]
Okey dokey, I added the scans. I'm going to try to make it more resilient to noise in the next few days and add some scans of pieces right side up. I still should do quite a bit of refactoring too. Let me know if you have questions!
