### ISSUE TITLE
OpenCV 2.4.6 cmake script does not work on Mac Mavericks

### ISSUE THREAD

**Issue by mengdiwang** [jzeimen/PuzzleSolver#2]
Some errors occur when building OpenCV 2.4.6, and they were solved by the following cmake script:

cmake -G "Unix Makefiles" -D CMAKE_INSTALL_PREFIX=/Users/produit/Library/Developer/opencv/ -D CMAKE_OSX_ARCHITECTURES=x86_64 -D BUILD_PERF_TESTS=OFF -D BUILD_opencv_legacy=NO ..

link: http://stackoverflow.com/questions/19578954/building-opencv-2-4-6-on-mac-mavericks

**Comment by jzeimen** [comment]
Thanks. I'll put this on the readme
